// FIIT Co. diagram registry — 12 diagrams across 6 doc keys.
// Ported verbatim from deploy/portfolio/fiit-diagram-data.jsx.

import { E, N, type DiagramEntry } from "./types";

export const DIAGRAM_REGISTRY: Record<string, DiagramEntry[]> = {
  arch: [
    {
      kind: "flow",
      title: "System Context",
      config: {
        legend: [
          ["actor", "Human / crawler"],
          ["platform", "The platform"],
          ["ext", "Third-party service"],
        ],
        groups: [
          { label: "External world", members: ["mem", "adm", "ins", "goo"] },
          { label: "Third-party services", members: ["ver", "cf", "res", "gsc", "mb"] },
        ],
        nodes: [
          N("mem", 0, 0, "Prospective Member", "actor", { sub: "community" }),
          N("adm", 0, 1, "Admin (Arden)", "actor"),
          N("ins", 0, 2, "Instructor", "actor", { sub: "~12 trainers" }),
          N("goo", 0, 3, "Google Search", "actor"),
          N("plat", 1, 1, "FIIT Co. Digital Platform", "platform", {
            rs: 2,
            sub: "Two Next.js sites · one Convex backend",
          }),
          N("ver", 2, 0, "Vercel", "ext", { sub: "hosting" }),
          N("cf", 2, 1, "Cloudflare", "ext", { sub: "DNS" }),
          N("res", 2, 2, "Resend", "ext", { sub: "email" }),
          N("gsc", 2, 3, "Search Console", "ext", { sub: "SEO" }),
          N("mb", 2, 4, "MindBody", "ext", { sub: "bookings · no API" }),
        ],
        edges: [
          E("mem", "plat", "browse, submit"),
          E("adm", "plat", "operate"),
          E("ins", "plat", "own schedule"),
          E("goo", "plat", "index"),
          E("plat", "ver", "deploys"),
          E("plat", "cf", "DNS"),
          E("plat", "res", "reset email"),
          E("plat", "gsc", "SEO"),
          E("adm", "mb", "manual reconcile", true),
        ],
      },
    },
    {
      kind: "flow",
      title: "Container Architecture",
      config: {
        unit: { NW: 150, NH: 66, HG: 40, VG: 52 },
        legend: [
          ["actor", "User"],
          ["platform", "Front-end"],
          ["pub", "Public fns"],
          ["authed", "Authed fns"],
          ["admin", "Admin fns"],
          ["db", "Database"],
          ["ext", "External"],
        ],
        groups: [
          { label: "Users", members: ["mem", "adm", "ins"] },
          { label: "Front-ends · Next.js on Vercel", members: ["cust", "staff"] },
          { label: "Backend · Convex", members: ["pub", "authed", "adm2", "db"] },
          { label: "External services", members: ["cf", "res", "gsc", "mb"] },
        ],
        nodes: [
          N("mem", 0, 0, "Member", "actor", { sub: "anonymous" }),
          N("adm", 1, 0, "Admin", "actor"),
          N("ins", 2, 0, "Instructor", "actor"),
          N("cust", 0, 1, "Customer Site", "platform", { sub: "fiitco.ca · indexed" }),
          N("staff", 2, 1, "Staff Portal", "platform", { sub: "staff.fiitco.ca · de-indexed" }),
          N("pub", 0, 2, "PUBLIC", "pub", { sub: "~25 fns · anon" }),
          N("authed", 1, 2, "AUTHED", "authed", { sub: "~40 fns" }),
          N("adm2", 2, 2, "ADMIN", "admin", { sub: "~100 fns" }),
          N("db", 1, 3, "Database", "db", { sub: "28 tables · 4 domains" }),
          N("cf", 0, 4, "Cloudflare", "ext", { sub: "DNS" }),
          N("res", 1, 4, "Resend", "ext"),
          N("gsc", 2, 4, "Search Console", "ext"),
          N("mb", 3, 4, "MindBody", "ext", { sub: "no API" }),
        ],
        edges: [
          E("mem", "cust", "HTTPS"),
          E("adm", "staff", "HTTPS + token"),
          E("ins", "staff", "HTTPS + token"),
          E("cust", "pub", "anon queries + 2 forms"),
          E("staff", "pub"),
          E("staff", "authed", "authed calls"),
          E("staff", "adm2", "admin calls"),
          E("pub", "db"),
          E("authed", "db"),
          E("adm2", "db"),
          E("authed", "res", "reset email", true),
          E("cust", "cf", "", true),
          E("gsc", "cust", "crawl", true),
          E("adm", "mb", "reconcile", true),
        ],
      },
    },
    {
      kind: "flow",
      title: "Data Domain View",
      config: {
        unit: { NW: 160, NH: 74, HG: 54, VG: 40 },
        legend: [
          ["web", "Customer site"],
          ["admin", "Staff portal"],
          ["db", "Operational"],
          ["auth", "Auth"],
          ["form", "Customer forms"],
        ],
        groups: [
          { label: "Customer site · fiitco.ca", members: ["c1", "c2", "c3", "c4"] },
          { label: "Staff portal · staff.fiitco.ca", members: ["s1", "s2", "s3"] },
          { label: "Data domains", members: ["ops", "web", "auth", "form"] },
        ],
        nodes: [
          N("c1", 0, 0, "Read public content", "web"),
          N("c2", 0, 1, "Submit referral", "web"),
          N("c3", 0, 2, "Submit guest-pass", "web"),
          N("c4", 0, 3, "Sign in", "web"),
          N("s1", 1, 0, "Manage auth", "admin"),
          N("s2", 1, 1, "Operate the studio", "admin"),
          N("s3", 1, 2, "Edit website content", "admin"),
          N("ops", 2, 0, "Operational", "db", { sub: "15 tables" }),
          N("web", 2, 1, "Website content", "web", { sub: "12 tables" }),
          N("auth", 2, 2, "Auth & security", "auth", { sub: "4 tables" }),
          N("form", 2, 3, "Customer forms", "form", { sub: "2 tables" }),
        ],
        edges: [
          E("s2", "ops", "read + write"),
          E("s3", "web", "read + write"),
          E("s1", "auth", "read + write"),
          E("s2", "form", "read"),
          E("c1", "web", "read only", true),
          E("c1", "ops", "websiteSchedule", true),
          E("c2", "form", "insert"),
          E("c3", "form", "insert"),
          E("c4", "auth", "login", true),
        ],
      },
    },
    {
      kind: "seq",
      title: "Auth & Session Lifecycle",
      config: {
        actors: [
          { id: "U", label: "User (browser)" },
          { id: "SP", label: "Staff Portal" },
          { id: "CX", label: "Convex auth.ts" },
          { id: "DB", label: "Database" },
          { id: "R", label: "Resend" },
        ],
        step: 56,
        laneW: 202,
        messages: [
          { kind: "note", from: "CX", text: "Login flow" },
          { from: "U", to: "SP", text: "submit email + password" },
          { from: "SP", to: "CX", text: "loginUser(email, pw)" },
          { from: "CX", to: "DB", text: "look up user by email" },
          { from: "CX", to: "DB", text: "check rateLimits (5 / 15 min)" },
          { kind: "note", from: "CX", text: "if rate-limited → reject" },
          { from: "CX", to: "CX", text: "PBKDF2-SHA256 verify (600k)" },
          { kind: "note", from: "CX", text: "if wrong pw → increment + reject" },
          { from: "CX", to: "DB", text: "insert session (32-byte, 14-day TTL)" },
          { from: "CX", to: "SP", text: "session token", kind: "return" },
          { from: "SP", to: "U", text: "store token in localStorage", kind: "return" },
          { kind: "note", from: "CX", text: "Authenticated calls" },
          { from: "U", to: "SP", text: "any signed-in action" },
          { from: "SP", to: "CX", text: "call fn with token" },
          { from: "CX", to: "CX", text: "requireAuth(token)" },
          { from: "CX", to: "DB", text: "update lastSeenAt (sliding 14d)" },
          { from: "CX", to: "SP", text: "execute + return", kind: "return" },
          { kind: "note", from: "CX", text: "Forgot password" },
          { from: "U", to: "SP", text: "forgot-password submit" },
          { from: "SP", to: "CX", text: "requestPasswordReset(email)" },
          { from: "CX", to: "DB", text: "insert single-use token (15-min TTL)" },
          { from: "CX", to: "R", text: "sendResetEmail(link)" },
          { from: "R", to: "U", text: "deliver reset email" },
          { from: "U", to: "SP", text: "click link, submit new pw" },
          { from: "SP", to: "CX", text: "resetPasswordWithToken" },
          { from: "CX", to: "DB", text: "validate + re-hash + mark used" },
          { from: "CX", to: "SP", text: "success", kind: "return" },
        ],
      },
    },
    {
      kind: "flow",
      title: "Deployment Topology",
      config: {
        unit: { NW: 158, NH: 66, HG: 42, VG: 50 },
        legend: [
          ["web", "Customer"],
          ["admin", "Staff / prod"],
          ["platform", "Vercel"],
          ["good", "Dev"],
          ["ext", "External"],
          ["authed", "Local dev"],
        ],
        groups: [
          { label: "Browser", members: ["bc", "bs"] },
          { label: "Cloudflare (DNS + edge)", members: ["cf"] },
          { label: "Vercel (hosting)", members: ["vc", "vs"] },
          { label: "Convex (backend)", members: ["prod", "dev"] },
          { label: "External", members: ["res", "gsc"] },
          { label: "Developer machine", members: ["lc", "ls"] },
        ],
        nodes: [
          N("bc", 0, 0, "fiitco.ca", "web", { sub: "customer HTML+JS" }),
          N("bs", 1, 0, "staff.fiitco.ca", "admin", { sub: "+ localStorage token" }),
          N("cf", 0, 1, "Cloudflare DNS + edge", "ext", { cs: 2, sub: "www → apex 308" }),
          N("vc", 0, 2, "fiit-website", "platform", { sub: "env NOT persisted" }),
          N("vs", 1, 2, "Fiitco-Operation", "platform", { sub: "env persisted" }),
          N("prod", 0, 3, "Convex Production", "admin", { sub: "dutiful-ferret-681" }),
          N("dev", 1, 3, "Convex Development", "good", { sub: "fabulous-goldfish-633" }),
          N("res", 0, 4, "Resend", "ext", { sub: "RESEND_API_KEY" }),
          N("gsc", 1, 4, "Search Console", "ext"),
          N("lc", 0, 5, "local :3001", "authed"),
          N("ls", 1, 5, "local :3000", "authed"),
        ],
        edges: [
          E("bc", "cf", "HTTPS"),
          E("bs", "cf", "HTTPS"),
          E("cf", "vc"),
          E("cf", "vs"),
          E("vc", "prod", "prod calls"),
          E("vs", "prod", "prod calls"),
          E("prod", "res", "outbound"),
          E("prod", "gsc", "sitemap", true),
          E("lc", "dev", "dev", true),
          E("ls", "dev", "dev", true),
        ],
      },
    },
  ],

  erd: [
    {
      kind: "flow",
      title: "Entity-Relationship Diagram · 28 tables",
      config: {
        unit: { NW: 152, NH: 70, HG: 40, VG: 54 },
        legend: [
          ["auth", "Auth & security (4)"],
          ["db", "Operational (15)"],
          ["web", "Website content (12)"],
          ["form", "Customer forms (2)"],
        ],
        groups: [
          { label: "Auth & security", members: ["users", "sessions", "prt", "rl"] },
          {
            label: "Operational",
            members: [
              "categories", "subcategories", "tiers", "classes", "instructors",
              "equipment", "weeklySchedule", "classPrograms", "exercises",
              "deliveryLog", "availability", "pathways", "availabilityExceptions",
              "clientJourneys", "pendingChanges",
            ],
          },
          {
            label: "Website content",
            members: [
              "trainers", "collaborators", "classFormats", "pricingPlans",
              "blogPosts", "locations", "testimonials", "faqEntries",
              "promoVideos", "websiteImages", "websiteSchedule", "legalDocs",
            ],
          },
          { label: "Customer forms", members: ["referrals", "guestPasses"] },
        ],
        nodes: [
          N("users", 0, 0, "users", null, { shape: "entity", dom: "auth", rows: [["email", "UK"], ["role"], ["instructorId", "FK"]] }),
          N("sessions", 0, 1, "sessions", null, { shape: "entity", dom: "auth", rows: [["token", "UK"], ["userId", "FK"]] }),
          N("prt", 0, 2, "passwordResetTokens", null, { shape: "entity", dom: "auth", rows: [["token", "UK"], ["userId", "FK"]] }),
          N("rl", 0, 3, "rateLimits", null, { shape: "entity", dom: "auth", rows: [["key", "UK"], ["count"]] }),
          N("referrals", 0, 5, "referrals", null, { shape: "entity", dom: "form", rows: [["referrer"], ["status"]] }),
          N("guestPasses", 0, 6, "guestPasses", null, { shape: "entity", dom: "form", rows: [["memberPhone"], ["monthKey"]] }),
          N("categories", 1, 0, "categories", null, { shape: "entity", dom: "ops", rows: [["categoryId", "UK"], ["name"]] }),
          N("subcategories", 2, 0, "subcategories", null, { shape: "entity", dom: "ops", rows: [["subcategoryId", "UK"], ["categoryId", "FK"]] }),
          N("tiers", 3, 0, "tiers", null, { shape: "entity", dom: "ops", rows: [["tierId", "UK"], ["name"]] }),
          N("classes", 1, 1, "classes", null, { shape: "entity", dom: "ops", rows: [["classId", "UK"], ["categoryId", "FK"]] }),
          N("instructors", 2, 1, "instructors", null, { shape: "entity", dom: "ops", rows: [["instructorId", "UK"], ["fullName"]] }),
          N("equipment", 3, 1, "equipment", null, { shape: "entity", dom: "ops", rows: [["equipmentId", "UK"], ["qty"]] }),
          N("weeklySchedule", 1, 2, "weeklySchedule", null, { shape: "entity", dom: "ops", rows: [["classId", "FK"], ["instructorId", "FK"]] }),
          N("classPrograms", 2, 2, "classPrograms", null, { shape: "entity", dom: "ops", rows: [["classId", "FK"], ["status"]] }),
          N("exercises", 3, 2, "exercises", null, { shape: "entity", dom: "ops", rows: [["exerciseId", "UK"], ["tier"]] }),
          N("deliveryLog", 1, 3, "deliveryLog", null, { shape: "entity", dom: "ops", rows: [["classId", "FK"], ["attendance"]] }),
          N("availability", 2, 3, "availability", null, { shape: "entity", dom: "ops", rows: [["instructorId", "FK"], ["dayOfWeek"]] }),
          N("pathways", 3, 3, "pathways", null, { shape: "entity", dom: "ops", rows: [["pathwayId", "UK"], ["weeks"]] }),
          N("availabilityExceptions", 1, 4, "availabilityExceptions", null, { shape: "entity", dom: "ops", rows: [["instructorId", "FK"], ["date"]] }),
          N("clientJourneys", 2, 4, "clientJourneys", null, { shape: "entity", dom: "ops", rows: [["journeyId", "UK"], ["pathwayId", "FK"]] }),
          N("pendingChanges", 3, 4, "pendingChanges", null, { shape: "entity", dom: "ops", rows: [["tableName"], ["status"]] }),
          N("trainers", 4, 0, "trainers", null, { shape: "entity", dom: "web", rows: [["slug", "UK"], ["name"]] }),
          N("collaborators", 5, 0, "collaborators", null, { shape: "entity", dom: "web", rows: [["slug", "UK"], ["confirmed"]] }),
          N("classFormats", 4, 1, "classFormats", null, { shape: "entity", dom: "web", rows: [["slug", "UK"], ["category"]] }),
          N("pricingPlans", 5, 1, "pricingPlans", null, { shape: "entity", dom: "web", rows: [["slug", "UK"], ["price"]] }),
          N("blogPosts", 4, 2, "blogPosts", null, { shape: "entity", dom: "web", rows: [["slug", "UK"], ["status"]] }),
          N("locations", 5, 2, "locations", null, { shape: "entity", dom: "web", rows: [["slug", "UK"], ["isPrimary"]] }),
          N("testimonials", 4, 3, "testimonials", null, { shape: "entity", dom: "web", rows: [["firstName"], ["rating"]] }),
          N("faqEntries", 5, 3, "faqEntries", null, { shape: "entity", dom: "web", rows: [["question"], ["active"]] }),
          N("promoVideos", 4, 4, "promoVideos", null, { shape: "entity", dom: "web", rows: [["youtubeId"], ["pageSlot"]] }),
          N("websiteImages", 5, 4, "websiteImages", null, { shape: "entity", dom: "web", rows: [["slot", "UK"], ["altText"]] }),
          N("websiteSchedule", 4, 5, "websiteSchedule", null, { shape: "entity", dom: "web", rows: [["dayOfWeek"], ["className"]] }),
          N("legalDocs", 5, 5, "legalDocs", null, { shape: "entity", dom: "web", rows: [["slug", "UK"], ["effectiveDate"]] }),
        ],
        edges: [
          E("users", "sessions", "1:N"),
          E("users", "prt", "1:N"),
          E("users", "rl", "1:N"),
          E("users", "instructors", "1:0..1"),
          E("categories", "subcategories", "1:N"),
          E("categories", "classes", "1:N"),
          E("tiers", "classes", "1:N"),
          E("classes", "weeklySchedule", "1:N"),
          E("instructors", "weeklySchedule", "1:N"),
          E("classes", "deliveryLog", "1:N"),
          E("instructors", "deliveryLog", "1:N"),
          E("pathways", "clientJourneys", "1:N"),
        ],
      },
    },
  ],

  dfd: [
    {
      kind: "flow",
      title: "Level 0 · Context DFD",
      config: {
        unit: { NW: 162, NH: 76, HG: 92, VG: 100 },
        legend: [
          ["ext", "External entity"],
          ["platform", "Process"],
        ],
        nodes: [
          N("m", 0, 0, "Prospective Member", "ext"),
          N("a", 0, 1, "Admin (Arden)", "ext"),
          N("i", 0, 2, "Instructor", "ext"),
          N("p0", 1, 1, "0.0 FIIT Co. Digital Platform", "platform", { shape: "process", d: 150 }),
          N("g", 2, 0, "Google Crawler", "ext"),
          N("r", 2, 1, "Resend", "ext"),
          N("mb", 2, 2, "MindBody", "ext"),
        ],
        edges: [
          E("m", "p0", "referral · guest-pass · login"),
          E("p0", "m", "public content"),
          E("a", "p0", "class / content edits"),
          E("p0", "a", "reports · queue"),
          E("i", "p0", "attendance · availability"),
          E("p0", "i", "my-classes · schedule"),
          E("g", "p0", "crawl"),
          E("p0", "g", "HTML + sitemap"),
          E("p0", "r", "reset email"),
          E("r", "p0", "delivery status"),
          E("mb", "a", "bookings (manual)", true),
        ],
      },
    },
    {
      kind: "flow",
      title: "Level 1 · Process breakdown",
      config: {
        unit: { NW: 152, NH: 66, HG: 86, VG: 70 },
        legend: [
          ["ext", "External entity"],
          ["platform", "Process"],
          ["db", "Data store"],
        ],
        nodes: [
          N("m", 0, 0, "Member", "ext"),
          N("g", 0, 1, "Google", "ext"),
          N("a", 0, 3, "Admin", "ext"),
          N("i", 0, 5, "Instructor", "ext"),
          N("p1", 1, 0, "1.0 Serve Public Content", "platform", { shape: "process", d: 108 }),
          N("p2", 1, 1, "2.0 Capture Form", "platform", { shape: "process", d: 108 }),
          N("p3", 1, 2, "3.0 Authenticate", "platform", { shape: "process", d: 108 }),
          N("p7", 1, 3, "7.0 Send Reset Email", "platform", { shape: "process", d: 108 }),
          N("p4", 1, 4, "4.0 Manage Operations", "platform", { shape: "process", d: 108 }),
          N("p5", 1, 5, "5.0 Edit Website", "platform", { shape: "process", d: 108 }),
          N("p6", 1, 6, "6.0 Record Delivery", "platform", { shape: "process", d: 108 }),
          N("d1", 2, 0, "D1 · Website content", "db", { shape: "store", sub: "12 tables" }),
          N("d4", 2, 1, "D4 · Customer forms", "db", { shape: "store", sub: "2 tables" }),
          N("d3", 2, 3, "D3 · Auth & sessions", "db", { shape: "store", sub: "4 tables" }),
          N("d2", 2, 5, "D2 · Operational", "db", { shape: "store", sub: "15 tables" }),
          N("r", 3, 3, "Resend", "ext"),
        ],
        edges: [
          E("m", "p1", "page req"),
          E("p1", "d1", "read"),
          E("p1", "d2", "websiteSchedule"),
          E("g", "p1", "crawl"),
          E("m", "p2", "submit"),
          E("p2", "d4", "insert"),
          E("m", "p3", "login/reset"),
          E("p3", "d3", "session"),
          E("p3", "p7", "trigger"),
          E("p7", "d3", "read email"),
          E("p7", "r", "email"),
          E("a", "p4", "CRUD"),
          E("p4", "d2", "read/write"),
          E("a", "p5", "edits"),
          E("p5", "d1", "read/write"),
          E("i", "p6", "attendance"),
          E("p6", "d2", "append"),
        ],
      },
    },
  ],

  fdd: [
    {
      kind: "flow",
      title: "Functional Decomposition · L0 → L2",
      config: {
        unit: { NW: 176, NH: 60, HG: 30, VG: 74 },
        nodes: [
          N("root", 2, 0, "FIIT Co. Digital Platform", "platform", { cs: 2 }),
          N("b1", 0, 1, "1. Manage Studio Operations", null, {
            shape: "entity", dom: "ops",
            rows: [["1.1 Schedule Management"], ["1.2 Instructor Management"], ["1.3 Class Catalogue"], ["1.4 Attendance Recording"], ["1.5 Programming"]],
          }),
          N("b2", 1, 1, "2. Publish Public Content", null, {
            shape: "entity", dom: "web",
            rows: [["2.1 Trainer Bios"], ["2.2 Programs & Pricing"], ["2.3 Blog"], ["2.4 Locations / FAQ / Legal"], ["2.5 Media"]],
          }),
          N("b3", 2, 1, "3. Engage Members", null, {
            shape: "entity", dom: "form",
            rows: [["3.1 Refer-a-Friend"], ["3.2 Guest Pass"], ["3.3 Contact Submissions"]],
          }),
          N("b4", 3, 1, "4. Control Access", null, {
            shape: "entity", dom: "auth",
            rows: [["4.1 Sign-In"], ["4.2 Sign-Up + Approval"], ["4.3 Password Reset"], ["4.4 Role & Session"]],
          }),
          N("b5", 4, 1, "5. Report & Observe", null, {
            shape: "entity", dom: "ops",
            rows: [["5.1 Attendance Reports"], ["5.2 Pending-Changes Queue"], ["5.3 Missing-Delivery Alerts"]],
          }),
          N("b6", 5, 1, "6. Administer Platform", null, {
            shape: "entity", dom: "auth",
            rows: [["6.1 User Administration"], ["6.2 Content Moderation"], ["6.3 Backup & Migration"]],
          }),
        ],
        edges: [E("root", "b1"), E("root", "b2"), E("root", "b3"), E("root", "b4"), E("root", "b5"), E("root", "b6")],
      },
    },
  ],

  usecase: [
    {
      kind: "flow",
      title: "Use Case Diagram · 22 use cases",
      config: {
        unit: { NW: 158, NH: 56, HG: 68, VG: 36 },
        legend: [
          ["actor", "Actor"],
          ["pub", "Anonymous"],
          ["authed", "Shared auth"],
          ["admin", "Admin only"],
          ["db", "Instructor only"],
        ],
        groups: [
          {
            label: "FIIT Co. Digital Platform",
            members: [
              "ubrowse", "uref", "ugp", "usignup", "usignin", "ureset", "uauth",
              "umgsch", "umgcls", "umginst", "umgwc", "umgusr", "uapprv",
              "umgref", "ureport", "ubackup", "umysch", "uatt", "uavail", "ulp",
            ],
          },
        ],
        nodes: [
          N("m", 0, 0, "Member / Prospect", "actor", { shape: "circle", d: 104 }),
          N("u", 0, 4, "Authenticated User", "abstract", { shape: "circle", d: 104 }),
          N("a", 0, 6, "Admin (Arden)", "actor", { shape: "circle", d: 104 }),
          N("i", 0, 10, "Instructor", "actor", { shape: "circle", d: 104 }),
          N("ubrowse", 1, 0, "Browse Public Content", "pub", { shape: "pill" }),
          N("uref", 1, 1, "Submit Referral", "pub", { shape: "pill" }),
          N("ugp", 1, 2, "Request Guest Pass", "pub", { shape: "pill" }),
          N("usignup", 1, 3, "Sign Up", "pub", { shape: "pill" }),
          N("usignin", 1, 4, "Sign In", "pub", { shape: "pill" }),
          N("ureset", 1, 5, "Reset Password", "pub", { shape: "pill" }),
          N("uauth", 2, 4, "Authenticate Session", "authed", { shape: "pill" }),
          N("umgsch", 3, 0, "Manage Schedule", "admin", { shape: "pill" }),
          N("umgcls", 3, 1, "Manage Catalogue", "admin", { shape: "pill" }),
          N("umginst", 3, 2, "Manage Instructors", "admin", { shape: "pill" }),
          N("umgwc", 3, 3, "Manage Website Content", "admin", { shape: "pill" }),
          N("umgusr", 3, 5, "Manage Users", "admin", { shape: "pill" }),
          N("uapprv", 3, 6, "Approve Pending Change", "admin", { shape: "pill" }),
          N("umgref", 3, 7, "Manage Referrals & Passes", "admin", { shape: "pill" }),
          N("ureport", 3, 8, "Weekly Attendance Report", "admin", { shape: "pill" }),
          N("ubackup", 3, 9, "Export / Restore Data", "admin", { shape: "pill" }),
          N("umysch", 2, 9, "View My Schedule", "db", { shape: "pill" }),
          N("uatt", 2, 10, "Record Attendance", "db", { shape: "pill" }),
          N("uavail", 2, 11, "Set Availability", "db", { shape: "pill" }),
          N("ulp", 2, 12, "Submit Lesson Plan", "db", { shape: "pill" }),
        ],
        edges: [
          E("m", "ubrowse"), E("m", "uref"), E("m", "ugp"),
          E("m", "usignup"), E("m", "usignin"), E("m", "ureset"),
          E("a", "umgsch"), E("a", "umgcls"), E("a", "umginst"),
          E("a", "umgwc"), E("a", "umgusr"), E("a", "uapprv"),
          E("a", "umgref"), E("a", "ureport"), E("a", "ubackup"),
          E("i", "umysch"), E("i", "uatt"), E("i", "uavail"), E("i", "ulp"),
          E("umgsch", "uauth", "«include»", true),
          E("umgwc", "uauth", "«include»", true),
          E("umgusr", "uauth", "«include»", true),
          E("ureport", "uauth", "«include»", true),
          E("umysch", "uauth", "«include»", true),
          E("uatt", "uauth", "«include»", true),
          E("ulp", "uauth", "«include»", true),
          E("usignin", "ureset", "«extend»", true),
          E("uref", "umgref", "«extend»", true),
          E("a", "u", "is a"),
          E("i", "u", "is a"),
        ],
      },
    },
  ],

  fishbone: [
    {
      kind: "fish",
      title: "Ishikawa 6M · stale-cache incident (I-02)",
      config: {
        w: 1120,
        h: 540,
        problem: "Stale schedule served for ~24h on fiitco.ca after a mid-week update",
        cats: [
          { label: "People", tone: "actor", side: "top", causes: ["Admin published without knowing the edge cache", "No second reviewer (single admin)"] },
          { label: "Machine", tone: "authed", side: "top", causes: ["Vercel edge-cache TTL longer than expected", "No invalidation hook on CMS publish"] },
          { label: "Method", tone: "good", side: "top", causes: ["No revalidation step in the runbook", "No post-publish smoke test"] },
          { label: "Material", tone: "db", side: "bottom", causes: ["Free-tier lacks push invalidation", "Two schedule tables caused confusion"] },
          { label: "Measurement", tone: "auth", side: "bottom", causes: ["No monitoring of what was served", "Detected by member complaint"] },
          { label: "Environment", tone: "form", side: "bottom", causes: ["Mid-week change was rare, unrehearsed", "Single-admin, no peer challenge"] },
        ],
      },
    },
  ],
};

// Ordered manifest matching the A8 diagrams page layout
export const DIAGRAM_MANIFEST: {
  id: string;
  group: string;
  code: string;
  title: string;
  entries: DiagramEntry[];
  meta: string;
}[] = [
  { id: "arch", group: "Architecture", code: "BA-08b · System Architecture", title: "System Architecture", entries: DIAGRAM_REGISTRY.arch, meta: "5 diagrams" },
  { id: "erd", group: "Data", code: "BA-08 · Entity-Relationship", title: "Entity-Relationship Diagram", entries: DIAGRAM_REGISTRY.erd, meta: "28 tables" },
  { id: "dfd", group: "Data", code: "BA-08c · Data Flow", title: "Data Flow Diagram (L0 + L1)", entries: DIAGRAM_REGISTRY.dfd, meta: "L0 + L1" },
  { id: "fdd", group: "Function & Behaviour", code: "BA-11b · Functional Decomposition", title: "Functional Decomposition", entries: DIAGRAM_REGISTRY.fdd, meta: "L0 → L2" },
  { id: "usecase", group: "Function & Behaviour", code: "BA-10b · Use Case", title: "Use Case Diagram", entries: DIAGRAM_REGISTRY.usecase, meta: "22 use cases" },
  { id: "fishbone", group: "Analysis", code: "BA-06b · Fishbone (Ishikawa)", title: "Fishbone Diagram", entries: DIAGRAM_REGISTRY.fishbone, meta: "6M · I-02" },
];
